image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - atlassian.atlascode
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - gitkraken.gitkraken-authentication
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - Orta.vscode-jest
    - redhat.vscode-yaml
    - streetsidesoftware.code-spell-checker
